[build]
  command = "npm run build"
  publish = "dist"

# Static product pages
[[redirects]]
  from = "/Autoprime-Surface-Pumps"
  to = "/Autoprime.html"
  status = 200

[[redirects]]
  from = "/Product-Page"
  to = "/product.html"
  status = 200

# SPA catch-all (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
