[build]
  publish = "."
  command = ""
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/Autoprime.html"
  to = "/Autoprime.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
