[[redirects]]
  from = "/autoprime-surface-pumps" # <-- Match the exact URL you are clicking
  to = "/Autoprime.html"            # <-- The file you want to serve
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
